export const TestCretionReqData = {
  accountCharges: [],
  accountCreateBranchOrganizationLevelId: 22,
  accountCreateBranchOrganizationLevelName: "Regional Branches",
  accountDescription: "n",
  accountOpenBranchOrganizationLevelId: 22,
  accountOpenBranchOrganizationLevelName: "Regional Branches",
  accountProductCode: "NICA",
  accountSubType: 0,
  accountType: "SAVINGS",
  balanceRestrictedStatus: "Yes",
  bufferAmount: 1,
  casaAccountName: "dinura",
  casaAccountOpenedDate: "2020/09/15",
  casaAccountRemarks: [],
  casaAccountTypeDescription: "",
  casaAllowMinusBalance: "Yes",
  casaAnticipatedFrequencyId: 2,
  casaAnticipatedValue: "1000-499999",
  casaAnticipatedValueId: 29,
  casaApplicantDetails: [
    {
      casaAccountRole: "",
      casaApplicantStatus: "ACTIVE",
      casaBeneficialOwnership: "",
      casaCustomerCode: "BANK1",
      casaCustomerId: 373,
      casaCustomerName: "SAdinma SAdinma",
      casaFullLegalName: "S.N. Senithi SAdinma",
      casaOwnershipType: "SOLE OWNER",
      guardianDetail: [{ guardianId: 383, guardianName: "Sahani Madushani" }],
      signatureId: 0,
      taxPercerntage: 100,
      casaKycStatus: "ACTIVE",
    },
  ],
  casaAtmDetails: [
    {
      id: 0,
      blockTransactions: "Yes",
      cardCollectionType: "Branch",
      cardExpireDate: "2020/09/30",
      cardFeeEnabled: "Yes",
      cardIssuedDate: "2020/09/15",
      cardNumber: "1234567812345678",
      cardType: "testcardnew",
      cardTypeId: 0,
      collectionPoint: "temp dev",
      collectionPointId: 80,
      foreignTransactionEnabled: "Yes",
      issuedBy: "ishanka",
      nameOnCard: "hgv",
      posEnabled: "Yes",
      remarks: "n",
      schemeType: "Amex1",
      schemeTypeId: 66572668,
      status: "ACTIVE",
      widrawalLimit: "465",
    },
  ],
  casaAutoChequeBookRequestEnabled: "Yes",
  casaAutoChequeBookRequestPeriod: "12",
  casaAutoChequeBookRequestPeriodFrequency: 202,
  casaCreatedBranch: 0,
  casaCurrency: "1",
  casaCurrencyCode: "LKR",
  casaCurrencyNumeric: "144",
  casaCustomer: 0,
  casaEnableDisableInterestCalculation: "Yes",
  casaIntroducerDetails: [],
  casaIsATMEnabled: "Yes",
  casaIsChequeBookEnabled: "Yes",
  casaKycStatus: "Yes",
  casaMaxAllowedCheckBooksPerRequest: "1",
  casaMaxOverdraftLimit: "1",
  casaMinorAccountStatus: "Minor with restrictions",
  casaNickName: "asdsd",
  casaNoOfChequesPerBook: 1,
  casaNomineeDetails: [
    {
      casaCustomerId: 373,
      casaNomineeId: 383,
      casaNomineeName: "Surya Madushani",
      casaNomineeStatus: "YES",
      casaPropotionRatio: "",
      casaCustomerCode: "BANK2",
      identification: 383,
    },
  ],
  casaOfficerName: "ishanka",
  casaOpenBranch: 0,
  casaOperationInstructionsDetails: [
    {
      casaAmountFrom: "1",
      casaAmountTo: "2",
      casaModelOfOperation: "Owner",
      casaNoOfSignatures: "1",
      casaNotes: "",
      casaStatus: "",
      eligiblePersonDetails: [
        {
          accountNo: 376,
          personId: 376,
          personName: "Amala ramasinghe",
          proportion: 100,
          signatureId: 521,
          status: "ACTIVE",
        },
      ],
    },
  ],
  casaOwnershipType: "SOLE OWNER",
  casaProduct: 137,
  casaRestrictedStatus: "Yes",
  casaSchemeCode: "COMM",
  casaSourceOfFundsDetails: [
    {
      casaSourceOfFundDescription: "Rent houses",
      casaSourceOfFundId: 18,
      casaStatus: "ACTIVE",
      otherRemarks: "",
      primaryIndicator: "Yes",
    },
  ],
  casaStatementStatus: [
    {
      createdUser: "Nadeesha",
      deliveryFrequency: "WEEK",
      deliveryFrequencyDesc: "Test",
      deliveryMethod: 1485,
      deliveryMethodDescription: "By post",
      remarks: "",
      status: "ACTIVE",
      type: "1481",
      typeDescription: "Statements",
    },
  ],
  casaStopRequest: "Yes",
  casaSubProductCode: "OD07",
  casaSubProductId: 63212668,
  checkBookcategory: "",
  chequeBookStockTypeId: 3,
  chequeBookTypeId: 808,
  chequeTypeId: 864060,
  customerVisitRequired: "Yes",
  documentDetails: [],
  draftId: 0,
  interestCalculationStartDate: "2020/09/16",
  interestDetails: [],
  minimumAmountForSweeping: 0,
  noOfVisitPerPeriod: 1,
  notificationDetails: [
    {
      accountId: 0,
      addressId: 0,
      addressType: 0,
      contactNo: "",
      contactType: 1,
      customerId: 373,
      alertDetail: [
        {
          alertEvent: "Cabbage",
          eventCategory: "Transactional",
          status: "ACTIVE",
          transactionLimit: 533,
          eventId: 531,
        },
      ],
      notificationTypes: "AT02",
      status: "ACTIVE",
      contactId: 360,
    },
  ],
  officerId: 1,
  otherCurrencyTransactionAllowed: "Yes",
  overdraftAgreementDetails: {
    autoRenewalPeriodType: 0,
    autoRenewalTenor: 0,
    debitTransactionLimit: 0,
    enableAutoRenewal: "Yes",
    gracePeriodInDays: 0,
    overdraftStartDate: "",
    overdraftType: "Permanenant",
    periodType: 0,
    remarks: "",
    renewalLimit: 0,
    tenor: 0,
  },
  overdraftDetails: [
    {
      accountName: "K.K.K Satharasinghe",
      accountNo: "051100000207",
      casaStatus: "ACTIVE",
      propotion: 0,
    },
  ],
  periodMethod: 0,
  productType: "PERSONAL",
  purposeDetails: [
    {
      isActivated: true,
      primaryIndicator: "Yes",
      casaPurposeDescription: "Account purpose 01",
      casaPurposeId: 19,
      casaStatus: "ACTIVE",
    },
  ],
  recoveryAccountId: "",
  recoveryPercentage: 1,
  recurringSweepingAllowed: "Yes",
  reversalLimit: 0,
  secondaryAccountNo: "",
  specialRate: 0.01,
  sweepingEnabled: "Yes",
  sweepingLimit: 0,
  customizeInterestDate: "ACTIVE",
  otherPostingMethod: "INTERNAL",
  crebitInterestPostType: "Self",
  debitInterestPostType: "Self",
  casaEnableInterestOnOverdraft: "Yes",
};
