apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: central-cash-management-autoscaller
  namespace: fusionx-ui
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: central-cash-management
  minReplicas: 2
  maxReplicas: 6
  targetCPUUtilizationPercentage: 80
