export type WidgetTypes =
  | "TEXT_STRING"
  | "TEXTAREA"
  | "SELECT"
  | "NUMBER"
  | "CHECKBOX"
  | "SWITCH"
  | "REMOTE_SELECT"
  | "REMOTE_MULTI_SELECT"
  | "DATE"
  | "FILE_UPLOAD"
  | "FILE_DROPPER"
  | "CUSTOM"
  | "RADIO"
  | "CUSTOM_PHONE";
