apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: comn-supplies-entities-autoscaller
  namespace: fusionx-ui
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: comn-supplies-entities
  minReplicas: 2
  maxReplicas: 6
  targetCPUUtilizationPercentage: 80
